id: wp-config-exposed

info:
  name: WordPress Config Exposed Detection
  author: nuclei-templates
  severity: critical
  description: Détecte les fichiers wp-config.php exposés (credentials)
  tags: wordpress,credentials,exposed,no-auth,critical

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-config.php"
      - "{{BaseURL}}/wp-config.php.bak"
      - "{{BaseURL}}/wp-config.php.old"

    matchers:
      - type: word
        words:
          - "DB_PASSWORD"
          - "DB_NAME"
          - "define('DB_"
        condition: or

